### ISSUE TITLE
When converting from Code to ASM, Memory Addresses shows as Numbers

### ISSUE THREAD

**Issue by Zerowalker** [TheGag96/CodeWrite#1]
As Title says.

They still work, but it's not that great cause you have no idea what address it is by looking at those numbers.

I would suggest to convert it back to it's hex form.

Thanks:)

**Comment by TheGag96** [comment]
Oh hey, didn't think anyone would ever make an issue on here :S Can you give a short example? Thanks!

EDIT: Ah, do you mean for branches and things? To fix that I'd need to actually figure out where to place labels and stuff (which may not be too hard). I might revisit this soon and figure that out. Would be a nice feature.

**Comment by TheGag96** [comment]
Check out the latest release! I finally fixed it (better late than never I suppose lol).

**Comment by Zerowalker** [comment]
nice;D
