### ISSUE TITLE
Can't sucessfully re-convert ASM to Codes

### ISSUE THREAD

**Issue by Ebola16** [TheGag96/CodeWrite#3]
I'm not quite sure what I'm doing here but something doesn't seem right.

1. Copy the following codes in "Codes":
C284C9D4 00000027
2C070003 40820128
7C002000 41820120
2C040063 40A20010
2C000021 4182010C
4800010C 2C040021
40A20010 2C000063
418200F8 480000F8
2C040069 40A20010
2C000011 418200E4
480000E4 2C040011
40A20010 2C000069
418200D0 480000D0
2C04006A 40A20010
2C000009 418200BC
480000BC 2C040009
40A20010 2C00006A
418200A8 480000A8
2C04006B 40A20010
2C00000D 41820094
48000094 2C04000D
40A20010 2C00006B
41820080 48000080
2C04006C 40A20010
2C000000 4182006C
4800006C 2C040000
40A20010 2C00006C
41820058 48000058
2C04006D 40A20010
2C000005 41820044
48000044 2C040005
40A20010 2C00006D
41820030 48000030
2C040047 40A20010
2C00002F 4182001C
4800001C 2C04002F
40A20014 2C000047
41820008 48000008
7C802378 7C002000
60000000 00000000
C284C30C 00000027
2C070003 40820128
7C002000 41820120
2C040063 40A20010
2C000021 4182010C
4800010C 2C040021
40A20010 2C000063
418200F8 480000F8
2C040069 40A20010
2C000011 418200E4
480000E4 2C040011
40A20010 2C000069
418200D0 480000D0
2C04006A 40A20010
2C000009 418200BC
480000BC 2C040009
40A20010 2C00006A
418200A8 480000A8
2C04006B 40A20010
2C00000D 41820094
48000094 2C04000D
40A20010 2C00006B
41820080 48000080
2C04006C 40A20010
2C000000 4182006C
4800006C 2C040000
40A20010 2C00006C
41820058 48000058
2C04006D 40A20010
2C000005 41820044
48000044 2C040005
40A20010 2C00006D
41820030 48000030
2C040047 40A20010
2C00002F 4182001C
4800001C 2C04002F
40A20014 2C000047
41820008 48000008
7C802378 7C002000
60000000 00000000

2. Convert it to ASM (no errors raised)

3. Clear the codes from the "Codes" section

4. Convert the ASM back to Codes

5. Observe:
![Capture](https://user-images.githubusercontent.com/17330088/56776222-161a7280-6799-11e9-88cd-d1e72469b39d.PNG)

Either these errors are incorrect or they should have been raised when initially converting the codes to ASM. This code is SFX Unload Clone Check (Mewtwo/Lucario, Roy/Marth, Red Alloy/Captain Falcon, Blue Alloy/Zelda, Yellow Alloy/Mario, Green Alloy/Kirby) - Brawl Version [ds22, codes]. Taken from http://forums.kc-mm.com/Gallery/BrawlView.php?Number=217000

**Comment by Ebola16** [comment]
The problem seems to involve `lfs f20, -15604(r4)` since removing that allows code generation without errors.

**Comment by TheGag96** [comment]
What you posted there is two ASM codes. When I separate them, they disassemble and reassemble easily. The `lfs f20, -15604(r4)` thing is just the start of the second one.
